vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        game:
            uri_prefix: /uploads/game/card
            upload_destination: '%kernel.project_dir%/public/uploads/game/card'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
